<% require "dotenv"; Dotenv.load(".env") %>

service: demo-crystal-kemal
image: gambala/demo-crystal-kemal
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: kemal.gambala.pro
  app_port: 3000
  healthcheck:
    interval: 10
    path: /
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: arm64
